plugins {
    id 'java'
    id 'java-library'
}

group = 'ru.agapovla'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}