plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'ru.agapovla'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':engine')

    implementation 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

application {
    mainClass = 'ru.agapovla.squaregame.Main'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'ru.agapovla.squaregame.Main'
        )
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}